### ISSUE TITLE
[PEBKAC] Not sure how to set up settings.json

### ISSUE THREAD

**Issue by PrincessRTFM** [Headline/Discord-IRC-Relay#11]
I fully admit that this is user error in the extreme, but I really like the look of this program and I want to use it - I just don't know how. I tried setting up `settings.json` the best I could, and frankly had to guess at half of the options, but when I ran the executable, I got this:

`Unhandled Exception: Discord.Net.HttpException: The server responded with error 401: 401: Unauthorized`

Okay, so clearly I didn't give the bot the right authentication info for my account's bot app. But I copied the "client secret" off of my "authorized apps" page into the `DiscordBotToken` setting. So I don't know what I'm doing wrong.

Finally, I was planning to try and use this with a ZNC bouncer account that I have from a friend for my usual IRC server, but I don't know how to set an IRC server username/password for this program. Honestly, I'm not entirely clear on the purpose of any of these settings:

- `IRCAuthUser`
- `IRCLoginName`
- `IRCAuthString`

Can I get an example config file, or a description of the purpose (and preferably syntax: does the Discord channel setting need a `#` in front? What about the IRC channel?) of the settings available?

**Comment by Headline** [comment]
Absolutely. This hasn't been documented very well, but here's an example configuration with the sensitive details redacted. 

Your discord token should be the `token:` field, not the client secret.
![alt text](https://i.gyazo.com/3a1af1ae653ef9d54d57fff83f265122.png "Example 1")

## Breakdown
- IRCServer - server to connect to (example: irc.us.gamesurge.net)
- IRCPort - port to use for connection (example: 6667)
- IRCChannel - channel to link (example: #channel)
- IRCNick - nickname to use (example: discord-relay)
- IRCAuthUser - user to authenticate with (example: authserv@services.gamesurge.net)
- IRCLoginName - name used for authentication (example: discord-relay)
- IRCLogMessages - determines if messages should be logged
- IRCAuthString - string sent to IRCAuthUser for authentication (example: AUTH discord-relay XXXX)
- DiscordBotToken - token used to maintain discord bot session
- DiscordGuildName - server name that the bot should target 
- DiscordChannelName - channel in the server that the bot should target for relays 

## Example Config
```
{
  "IRCServer": "irc.us.gamesurge.net",
  "IRCPort": 6667,
  "IRCChannel": "#sourcemod",
  "IRCNick": "r",
  "IRCAuthUser": "authserv@services.gamesurge.net",
  "IRCLoginName": "discord-relay",
  "IRCLogMessages": true,
  "IRCAuthString": "AUTH discord-relay XXXXXXXXXXXX",
  "DiscordBotToken": "XXXXXXXXXXXXXXXXXXX",
  "DiscordGuildName": "sourcemod",
  "DiscordChannelName": "sourcemod"
}
```

**Comment by PrincessRTFM** [comment]
Ohhhh... Didn't know it needed an app bot user, though I should have guessed. Okay, two more things to note: it doesn't say anywhere that the relay can't use SSL, but it can't. I was trying to use port 6660 on the irc server and it was stalling with the message "Index is outside the bounds of the array" and no users were appearing _anywhere_. Second, I set `IRCLoginName` to `discord-relay` and it's still using my computer's user account as its login name.

Also, a suggestion? Make the relay handle account authentication _before_ joining the IRC channels, in case of, e.g. a vhost. I think there are also channel mods that can be set that require users to be registered to nickserv to join on certain servers. Basically:

```
if (irc_login_info_provided) {
	do_irc_login()
	wait_for_irc_login()
	join_irc_channel()
}
else {
	join_irc_channel()
}
```

And my last question (for now): is there a way to make one instance join multiple IRC channels? Not sure it'd make sense to do so, so I _fully_ understand if there isn't, just curious. Might be nice to be able to move the IRC bot to a different channel without shutdown/reconfigure/restart for the bot. (I know, I'm needy. Feel free to ignore this bit.)

**Comment by Headline** [comment]
Have you put the bot in your discord server? In other words, do you see it in the offline members? If not, that means that you haven't yet put it in there, and this is where the `clientid` comes into play. Use the link below, but replace YOUR_CLIENT_ID_HERE with the client id seen in this discord bot's application page on `https://discordapp.com/developers`. Then just pick which server to place the bot in

`https://discordapp.com/oauth2/authorize?&client_id=YOUR_CLIENT_ID_HERE&scope=bot&permissions=0`

**Comment by PrincessRTFM** [comment]
That was what I was missing. Okay, it works. Just those minor suggestions left, but feel free to ignore them. Thanks for the help setting it up, and thanks for making this bridge in the first place!
