### ISSUE TITLE
Blocking certain users from relaying

### ISSUE THREAD

**Issue by SugarD-x** [Headline/Discord-IRC-Relay#12]
Is it possible to block certain users from relaying messages? Right now I'm running into an issue where an application that posts to both IRC and Discord is being seen by the bot in IRC, and they are relaying it to Discord too.

**Comment by Headline** [comment]
Yes, I'll add a json configuration for a user blacklist for both discord & irc

**Comment by SugarD-x** [comment]
Thank you so much!
