### ISSUE TITLE
Bot offline - one way relay

### ISSUE THREAD

**Issue by xDemonessx** [Headline/Discord-IRC-Relay#13]
I'm experiencing an issue where the bot goes offline in Discord, thus messages typed in Discord do not appear on the IRC side. However, messages are still received and updated on the Discord side from IRC. 

Similar issues and discussions on relative projects:

https://github.com/reactiflux/discord-irc/issues/326 
https://github.com/reactiflux/discord-irc/issues/328

I am specifically relaying from the Rizon network, as network specific protocols have been referenced in the issues linked above it may be relevant. 

Is it possible to have the bot disconnect and reconnect automatically every 24 hours?

**Comment by Headline** [comment]
@xDemonessx The best thing you can do is to reload the bot with a cronjob or a reset script every 24 hours or so, but I have experienced this bug myself, too.

I believe we fall into this bug listed below, and am eager to find a solution as well. I'll continue looking into it and see if we can reliably hook failures
https://github.com/RogueException/Discord.Net/issues/960

**Comment by Headline** [comment]
This was completed in version 1.3

If for whatever reason this still happens, please re-open this issue.

**Comment by xDemonessx** [comment]
Thank you! I just updated and will let you know.
