### ISSUE TITLE
Not working on Windows 7

### ISSUE THREAD

**Issue by LaineZ** [Headline/Discord-IRC-Relay#8]
at startup it gives the message to the console, the bot connect in the IRC chat but in the discord the bot offline. Windows 7 x64. Last bot version
**Bot output in console:**
https://pastebin.com/kcSyxHdr
**Settings.xml:**
https://pastebin.com/AJ4QNd2y

**Comment by Headline** [comment]
Hello! Thanks for reporting this issue. 

The fix should be fairly simple, as it seems that .NET web sockets are funky on platforms earlier than Windows Vista. A new commit should land in a few minutes that hopefully solves your problems. 

Please let me know if it works.
